sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: eBdcra9P8Fb3dlpTMAbFMJygGky3gBG+AU23Ag1g/mgyD4/cdoEv+bgeSAOFm6H1mihQysQKZTI45kV4m0sxUmZwbW6c2fAGamVDYOpXUDRUGh56er3oAoKnmBLDnJys1y9TiMQBaLvI6hvgO0Eu+zcD6CMPHuRwVQ/0tFgu+9sYrvTWTErqDg8kh25Rz44gbUbxMi66RX4dbyHMOzbLc7VplYAfWj9gLwHplr7IpVoiFEbvqq1oHkl1SvbFRHdHh5tv4RQOqqihW+UiTd46uhKbARFerGKjDRNiJOiRqXgUFf2lhc6UkLZclolb/fc1z/66hqmCKm0Ka5Q4pzwZs9Q3u+hGHdagiblPjh/Jb/QUtYfJJB+85LBIdwaelTDzhb1eIfZIg2gB0RLw8m9WIhnHzPnnCe9u9L5G6qQFU3NZIu0DKMTphEAIVtgFtuZwaucoYGGjddVH+RzQq9d0NJxaSwHcaZm/wfb8//VspbRz8HzaUvT5dUsed0vLmXVUHWq6oCTabvAfzUb5SshVZ1ABTVB43VPXerbeY4H7/7enTYBpDTiB3ynngE2bOEMe94T7AK2FYA+iSkI039K+3Y3bSS2ZalwMw390zMxr9VkB+BYWperzTr6LYj781LIZ1PcLM2Se2kYJNdzvXrmcJyCUOPubl4Ici0tRZjh5Amk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Satyricon---Volume-04---Escape-by-Sea_5221
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy